[package]
name = "hello_world"
version = "0.0.1"
edition = "2021"
authors = ["Nehil Danis"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
